Repository 1Spirit1/Learn-Linux, pull requests merged in 2022-10, with the labels that each got.

#2 Create Flavours of Ubuntu.md
  Ununtu/Flavours of Ubuntu.md
Labels: documentation, hacktoberfest-2022, hacktoberfest-accepted

#4 New learning about Linux
  Ununtu/How to write and compile a C program in Linux.md
Labels: hacktoberfest-2022, hacktoberfest-accepted

#7 Added another two flavours of Ubuntu.
  Ubuntu/Flavours of Ubuntu.md
Labels: hacktoberfest-accepted

#11 Debian GNU/Linux
  Debian/Debian Command Cheat Sheet.md
  Debian/Features of Debian.md
  Debian/Installation Procedure for Debian Linux.md
  Debian/README.md
  Debian/Themes for Debian.md
Labels: hacktoberfest-2022, hacktoberfest-accepted

#13 Create installing-vs-code-in-ubuntu.md
  Ubuntu/installing-vs-code-in-ubuntu.md
Labels: hacktoberfest-accepted

#16 Linux- level up
  Linux Level-up/LInus level-up.md
Labels: hacktoberfest-2022, hacktoberfest-accepted

#18 Install Vm tools on Ubuntu
  Ubuntu/Install VM tools on Ubuntu.md
Labels: hacktoberfest-accepted

#14 Added some of the common commandline comands
  Ubuntu/BasicCommandLineCommands.md
Labels: hacktoberfest-2022, hacktoberfest-accepted

#21 Aman
  Ununtu/Basic Commands of Linux.md
  Ununtu/How to Set Environment Variables in Linux.md
Labels: hacktoberfest-2022, hacktoberfest-accepted

#24 Setting environment variables.
  Ubuntu/Set Environment Variables in Linux.md
Labels: hacktoberfest-accepted

#27 Update readme.md
  Ubuntu/readme.md
Labels: hacktoberfest-accepted

#26 content-arch-distro
  Manjaro/Community.md
  Manjaro/Editions.md
  Manjaro/Features.md
  Manjaro/Installing-VScode.md
  Manjaro/PackageManager.md
  Manjaro/readme.md
Labels: hacktoberfest-2022, hacktoberfest-accepted

#29 Added some content on fedora
  Fedora/Features_of_fedora.md
  Fedora/readme.md
Labels: hacktoberfest-accepted

#31 Linux Documantation added
  Linux Level-up/Linux Documentation.md
Labels: hacktoberfest-accepted

#33 Create LibreOffice Installation guide on Ubuntu.md
  Ubuntu/LibreOffice Installation guide on Ubuntu.md
Labels: hacktoberfest, hacktoberfest-accepted

#34 Create How_To_Install_Git_on_Ubuntu.md
  Ubuntu/How_To_Install_Git_on_Ubuntu.md
Labels: hacktoberfest

#35 Software To install in linux in one command
  Linux Level-up/Software To install in Linux in one Command.md
Labels: hacktoberfest

#38 Added Fedora Workstation 37
  Fedora/Fedora-37.md
Labels: hacktoberfest-accepted

#39 Linux Mint
  Mint/Cheatsheet of Mint.md
  Mint/Features of Mint.md
  Mint/Installation Process of Mint.md
  Mint/Themes Of Mint.md
  Mint/readme.md
Labels: hacktoberfest-accepted

#42 Created Install_Pycharm_Ubuntu.md file
  Ubuntu/Install_Pycharm_Ubuntu.md
Labels: hacktoberfest, hacktoberfest-accepted

#43 Adding Vi Commands
  Linux Level-up/VI EDITOR COMMANDS.md
Labels: hacktoberfest, hacktoberfest-accepted

#44 Added Black Arch Linux section and basic commands for Fedora Linux
  Black Arch Linux/Basic commands in Black Arch linux
  Black Arch Linux/Features of Black Arch linux
  Black Arch Linux/README.md
  Fedora/BasicCommandsInFedora.md
Labels: hacktoberfest

#45 Create How_To_Install_Node.js-on_Ubuntu.md
  Ubuntu/How_To_Install_Node.js-on_Ubuntu.md
Labels: hacktoberfest

#47 Arch Tutorial
  Arch Tutorial/README.md
  Arch Tutorial/dotfiles/backup.Xresources
  Arch Tutorial/dotfiles/i3/config
  Arch Tutorial/dotfiles/nitrogen/013.png
  Arch Tutorial/dotfiles/nitrogen/bg-saved.cfg
  Arch Tutorial/dotfiles/polybar/config
  Arch Tutorial/dotfiles/polybar/launch.sh
  Arch Tutorial/dotfiles/rofi/config.rasi
  Arch Tutorial/dotfiles/rofi/oxide.rasi
  Arch Tutorial/screenshot/add-albert-autostart.png
  Arch Tutorial/screenshot/albert-autostart.png
  Arch Tutorial/screenshot/arch.jpg
  Arch Tutorial/screenshot/aur-packages.png
  Arch Tutorial/screenshot/desktop-preview.png
  Arch Tutorial/screenshot/dotnet.png
  Arch Tutorial/screenshot/nvidia-search.png
  Arch Tutorial/screenshot/partition.png
  Arch Tutorial/screenshot/vanila-desktop.png
  Arch Tutorial/tmux.conf
  Arch Tutorial/vimrc
  Arch Tutorial/zshrc
Labels: hacktoberfest-accepted

#49 I/O Rediretion in linux
  Linux Level-up/Input Output Redirection in Linux.md
Labels: hacktoberfest-accepted

#52 Create 10_Things_To_Do_After_You_Have_Installed_Ubuntu.md
  Ubuntu/10_Things_To_Do_After_You_Have_Installed_Ubuntu.md
Labels: hacktoberfest-accepted

#53 Create Installing packages in Manjaro
  Manjaro/Installing packages in Manjaro
Labels: hacktoberfest-accepted
